---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api
spec:
  destination:
    name: "api"
  sources:
  - name: "web"
    action: allow
  #- name: web
  #  namespace: westus2-1
  #  partition: westus2-shared
  #  action: allow