---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: web1
spec:
  destination:
    name: web
  sources:
  - name: ingress-gateway
    namespace: default
    action: allow