---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: svc-studio-query
spec:
  destination:
    name: "svc-studio-query"
  sources:
  - name: "ui-studio"
    peer: consul1-westus2
    action: allow
  #- name: ui-studio
  #  namespace: westus2-1
  #  partition: westus2-shared
  #  action: allow