---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api
spec:
  destination:
    name: api
    namespace: eastus-1
  sources:
  - name: web
    namespace: eastus-1
    action: allow