apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: westus2-3
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: westus2-3
spec:
  selector:
    app: api
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: westus2-3
  labels:
    app: api
    version: v1
    service: fake-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      namespace: westus2-3
      labels:
        zone: westus2-3
        app: api
        service: fake-service
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'false'
        consul.hashicorp.com/service-tags: 'aks,v1'
        consul.hashicorp.com/service-meta-version: 'v1'
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              zone: westus2-3
              service: fake-service
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - westus2-3
      serviceAccountName: api
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.21.0
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9091'
            #- name: 'UPSTREAM_URIS'
            #  value: 'grpc://currency.currency-ns:9090,http://payments.payments-ns:9090'
            - name: 'NAME'
              value: 'api-v1'
            - name: 'MESSAGE'
              value: 'API response'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'TIMING_50_PERCENTILE'
              value: '20ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '30ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '40ms'
            - name: 'TIMING_VARIANCE'
              value: '10'
            - name: 'HTTP_CLIENT_APPEND_REQUEST'
              value: 'true'
            - name: 'TRACING_ZIPKIN'
              value: 'http://simplest-collector.default:9411'
